# --- CONFIGURACI\u00d3N PARA RAILWAY (Backend en la nube) ---
# spring.datasource.url=${MYSQL_URL}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# server.port=${PORT:8080}

# --- CONFIGURACI\u00d3N LOCAL (WampServer) ---
spring.datasource.url=jdbc:mysql://localhost:3306/escuela_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect