# --- CONFIGURACI\u00d3N PARA RAILWAY (Nombres manuales) ---
spring.datasource.url=jdbc:${MI_DB_URL}
spring.datasource.username=${MI_DB_USER}
spring.datasource.password=${MI_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# --- HIBERNATE Y DIALECTO ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true