# --- CONFIGURACI\u00d3N PARA RAILWAY (Separada) ---
spring.datasource.url=jdbc:${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect