version: '3.8'

services:
  # Base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-escuela
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escuela_api
    ports:
      - "3306:3306"
    volumes:
      - db_escuela_data:/var/lib/mysql
    restart: always

  # Backend Java Spring Boot
  api-escuela:
    build: .
    container_name: api-escuela-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASS: root
    restart: always

volumes:
  db_escuela_data:
